"""Shared datatypes used across the prompt cache implementation."""

from __future__ import annotations

from dataclasses import dataclass, field
import json
import time
from typing import Any


def _estimate_size_bytes(payload: Any) -> int:
    """Estimate serialized size for capacity tracking and metrics."""

    return len(json.dumps(payload, sort_keys=True, default=str).encode("utf-8"))


@dataclass(slots=True)
class CacheEntry:
    """Represents a cacheable prompt/response pair.

    Attributes:
        key: Deterministic cache key generated by ``CacheKeyBuilder``.
        value: Serialized LLM response payload or application-specific object.
        created_at: Unix epoch at insertion time.
        ttl: Time-to-live in seconds. ``None`` means no expiry.
        hit_count: Number of successful retrievals.
        metadata: Request and bookkeeping metadata.
        last_accessed: Unix epoch of the most recent access.
    """

    key: str
    value: Any
    created_at: float
    ttl: float | None
    hit_count: int = 0
    metadata: dict[str, Any] = field(default_factory=dict)
    last_accessed: float = field(default_factory=time.time)

    @property
    def expires_at(self) -> float | None:
        """Return the expiry timestamp if the entry has a TTL."""

        if self.ttl is None:
            return None
        return self.created_at + self.ttl

    def is_expired(self, now: float | None = None) -> bool:
        """Return ``True`` when the entry should no longer be served."""

        if self.ttl is None:
            return False
        current_time = time.time() if now is None else now
        return current_time >= self.created_at + self.ttl

    def size_bytes(self) -> int:
        """Return an approximate serialized size for the entry."""

        return _estimate_size_bytes(self.to_dict())

    def to_dict(self) -> dict[str, Any]:
        """Serialize the entry to a JSON-compatible dictionary."""

        return {
            "key": self.key,
            "value": self.value,
            "created_at": self.created_at,
            "ttl": self.ttl,
            "hit_count": self.hit_count,
            "metadata": self.metadata,
            "last_accessed": self.last_accessed,
        }

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "CacheEntry":
        """Deserialize a previously serialized cache entry."""

        return cls(
            key=payload["key"],
            value=payload.get("value"),
            created_at=float(payload["created_at"]),
            ttl=float(payload["ttl"]) if payload.get("ttl") is not None else None,
            hit_count=int(payload.get("hit_count", 0)),
            metadata=dict(payload.get("metadata", {})),
            last_accessed=float(payload.get("last_accessed", payload["created_at"])),
        )


@dataclass(slots=True)
class CompletionResult:
    """Result returned by the cache-aware LLM client."""

    response: Any
    cached: bool
    cache_key: str
    latency_ms: float
    tokens_used: int
    estimated_cost_usd: float
    semantic_hit: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class CacheStats:
    """Aggregated cache statistics suitable for health checks and dashboards."""

    total_requests: int
    cache_hits: int
    cache_misses: int
    evictions: int
    errors: int
    cache_size_bytes: int
    cache_item_count: int
    hit_rate: float
    avg_hit_latency_ms: float
    avg_miss_latency_ms: float
    avg_api_latency_ms: float
    gauges: dict[str, float] = field(default_factory=dict)


@dataclass(slots=True)
class WarmingResult:
    """Summary emitted by cache warming and dump/restore utilities."""

    loaded_entries: int
    skipped_entries: int
    duration_ms: float
    output_path: str | None = None
    errors: list[str] = field(default_factory=list)
